name: Build Artifacts

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - cmd/**
      - pkg/**
      - desktop/**
      - e2e/**
      - Cargo.toml
      - Cargo.lock
      - go.mod
      - go.sum

jobs:
  build-linux:
    name: Build Linux Artifacts ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v6

      - name: setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          host: ubuntu-latest
          target: ${{ matrix.target }}
          package_version: 0.0.0
          cli_only: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
          cache-key-suffix: "build-artifacts-${{ github.run_id }}"

      - name: build CLI
        uses: ./.github/actions/build-cli
        with:
          host: ubuntu-latest
          target: ${{ matrix.target }}
          os: linux
          arch: ${{ matrix.target == 'x86_64-unknown-linux-gnu' && 'amd64' || 'arm64' }}
          version: 0.0.0
          telemetry_private_key: ""
          crane_private_key: ""
          output_path: artifacts
          sidecar_path: desktop/src-tauri/bin

      - name: build desktop app
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: tauri-apps/tauri-action@v0.6
        with:
          projectPath: "./desktop"
          args: "--target ${{ matrix.target }} --config src-tauri/tauri-flatpak.conf.json --bundles appimage,deb,updater"
          includeUpdaterJson: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # resolves linuxdeploy build failure issue
          # https://github.com/tauri-apps/tauri/issues/8929
          NO_STRIP: true
          # TAURI_SIGNING_PRIVATE_KEY_PASSWORD:

      - name: upload CLI artifacts
        uses: actions/upload-artifact@v6
        with:
          name: linux-${{ matrix.target }}-cli
          path: artifacts/devpod-cli-*
          if-no-files-found: error
          retention-days: ${{ vars.BUILD_ARTIFACTS_RETENTION_DAYS || 3 }}

      - name: upload desktop app artifacts
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions/upload-artifact@v6
        with:
          name: linux-${{ matrix.target }}-desktop
          path: desktop/src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          retention-days: ${{ vars.BUILD_ARTIFACTS_RETENTION_DAYS || 3 }}
          if-no-files-found: warn

  build-macos:
    name: Build MacOS Artifacts ${{ matrix.target }}
    needs: [build-linux]
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v6

      - name: setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          host: macos-latest
          target: ${{ matrix.target }}
          package_version: 0.0.0
          cli_only: false
          cache-key-suffix: "build-artifacts-${{ github.run_id }}"

      - name: build CLI
        uses: ./.github/actions/build-cli
        with:
          host: macos-latest
          target: ${{ matrix.target }}
          os: darwin
          arch: ${{ matrix.target == 'x86_64-apple-darwin' && 'amd64' || 'arm64' }}
          version: 0.0.0
          telemetry_private_key: ""
          crane_private_key: ""
          output_path: artifacts
          sidecar_path: desktop/src-tauri/bin

      - name: build desktop app
        uses: tauri-apps/tauri-action@v0.6
        with:
          projectPath: "./desktop"
          args: "--target ${{ matrix.target }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # TAURI_SIGNING_PRIVATE_KEY_PASSWORD:

      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-${{ matrix.target }}
          path: |
            artifacts/devpod-cli-*
            desktop/src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          retention-days: ${{ vars.BUILD_ARTIFACTS_RETENTION_DAYS || 3 }}
          if-no-files-found: warn

  build-windows:
    name: Build Windows Artifacts
    needs: [build-linux]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          host: windows-latest
          target: x86_64-pc-windows-msvc
          package_version: 0.0.0
          cli_only: false
          cache-key-suffix: "build-artifacts-${{ github.run_id }}"

      - name: build CLI
        uses: ./.github/actions/build-cli
        with:
          host: windows-latest
          target: x86_64-pc-windows-msvc
          os: windows
          arch: amd64
          version: 0.0.0
          telemetry_private_key: ""
          crane_private_key: ""
          output_path: artifacts
          sidecar_path: desktop/src-tauri/bin

      - name: build desktop app
        uses: tauri-apps/tauri-action@v0.6
        with:
          projectPath: "./desktop"
          args: "--target x86_64-pc-windows-msvc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # TAURI_SIGNING_PRIVATE_KEY_PASSWORD:

      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: windows-x86_64
          path: |
            artifacts/devpod-cli-*
            desktop/src-tauri/target/x86_64-pc-windows-msvc/release/bundle/**/*
          retention-days: ${{ vars.BUILD_ARTIFACTS_RETENTION_DAYS || 3 }}
          if-no-files-found: warn
