name: Automatic Approve Workflow

on:
  workflow_dispatch:

jobs:
  automatic-approve:
    name: Automatic Approve Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          workflows: "commit.yml,lint.yml,pr-ci.yml,pre-commit.yml"
